- src: https://github.com/gvlproject/gvl.ansible.filesystem.presetup
- src: https://github.com/gvlproject/gvl.ansible.filesystem
- src: https://github.com/gvlproject/microgvl.ansible.filesystem
- src: https://github.com/gvlproject/gvl.ansible.image