- name: Update apt packages
  apt: update_cache=yes

- name: Install latest apt packages
  apt: upgrade=dist

- name: Install required system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - screen
    - environment-modules

- name: Ensure apt version of ansible is uninstalled
  apt: pkg=ansible state=absent

- name: Ensure pip version of ansible is uninstalled
  pip: name=ansible state=latest