- name: GVL Galaxy - Stop Galaxy
  shell: "{{ galaxy_server_dir }}/run.sh --stop-daemon"
  sudo: yes
  sudo_user: "{{ galaxy_user_name }}"

- name: Stop PostgreSQL
  shell: "{{ postgresql_bin_dir }}/pg_ctl -D {{ galaxy_db_dir }} stop"
  sudo: yes
  sudo_user: postgres

- name: GVL Galaxy - Create galaxy archive target directory
  file: dest="{{ galaxy_archive_path }}" owner={{ galaxy_user_name }} group={{ galaxy_user_name }} state=directory

- name: GVL Galaxy - Install openstack swift packages
  pip: name={{ item }} virtualenv="{{ galaxy_archive_path }}/venv"
  with_items:
    - python-swiftclient
    - python-keystoneclient

- name: GVL Galaxy - Remove existing archive
  file: dest="{{ galaxy_archive_path }}/{{ galaxy_archive_name }}" state=absent
  sudo: yes
  sudo_user: root

- name: GVL Galaxy - Create new filesystem archive
  command: chdir={{ galaxyFS_base_dir }} tar -czf {{ galaxy_archive_path }}/{{ galaxy_archive_name }} -C {{ galaxyFS_base_dir }} .
  sudo: yes
  sudo_user: root

- name: GVL Galaxy - Upload filesystem archive
  command: chdir={{ galaxy_archive_path }} {{ galaxy_archive_path }}/venv/bin/swift upload {{ cloudman_bucket_name }} {{ galaxy_archive_name }}
  sudo: yes
  sudo_user: root
  environment:
     OS_AUTH_URL: "{{ OS_AUTH_URL }}"
     OS_TENANT_ID: "{{ OS_TENANT_ID }}"
     OS_TENANT_NAME: "{{ OS_TENANT_NAME }}"
     OS_USERNAME: "{{ OS_USERNAME }}"
     OS_PASSWORD: "{{ OS_PASSWORD }}"
