- name: GVL Galaxy - Set genomespace urls to point to GVL versions
  replace: dest="{{ galaxy_server_dir }}/{{ item }}" regexp="dm.genomespace.org" replace="{{ gvl_genomespace_server }}"
  with_items:
    - tools/genomespace/genomespace_exporter.py
    - tools/genomespace/genomespace_file_browser.py
    - tools/genomespace/genomespace_importer.py
